export enum GovernmentDepartment {
    POULTRY = 'POULTRY',
    CROPS = 'CROPS',
    LIVESTOCK = 'LIVESTOCK',
    FISHERIES = 'FISHERIES',
    HORTICULTURE = 'HORTICULTURE',
    AGRIBUSINESS = 'AGRIBUSINESS',
    SUSTAINABILITY = 'SUSTAINABILITY',
    COMPLIANCE = 'COMPLIANCE',
    GENERAL = 'GENERAL'
  }