export enum ProjectCategory {
    POULTRY_FARMING = 'POULTRY_FARMING',
    CROP_PRODUCTION = 'CROP_PRODUCTION',
    LIVESTOCK_FARMING = 'LIVESTOCK_FARMING',
    FISH_FARMING = 'FISH_FARMING',
    VEGETABLE_FARMING = 'VEGETABLE_FARMING',
    FRUIT_FARMING = 'FRUIT_FARMING',
    AGRO_PROCESSING = 'AGRO_PROCESSING',
    SUSTAINABLE_AGRICULTURE = 'SUSTAINABLE_AGRICULTURE',
    ORGANIC_FARMING = 'ORGANIC_FARMING',
    GENERAL_AGRICULTURE = 'GENERAL_AGRICULTURE',
    CROPS = "CROPS"
}